paths:
  output_dir: "results"
  data_dir: "data_processed"
  model_dir: "results/models"
  figures_dir: "results/figures"
  tables_dir: "results/tables"
  drl_state_file: "results/spx_iv_drl_state.csv"

settings:
  start_date: "1996-01-01"
  end_date: "2023-12-31"
  fred_api_key: null

data:
  start_date: "1996-01-01"
  end_date: "2023-12-31"
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

features:
  target_col: "atm_iv_30d"
  all_feature_cols:
    - "garman_klass_rv"  # price volatility
    - "term_structure_slope"  # surface volatility
    - "iv_fpca1"
    - "iv_fpca2"
    - "iv_fpca3"
    - "VIXCLS"  # macro GDP proxy
    - "USEPUINDXD"  # macro inflation proxy
  categorical_cols: []
  price:
    window: 252  # 1 year of trading days
    min_periods: 126
  surface:
    maturities: [30, 60, 90, 180, 365]  # days
    moneyness_range: [-0.2, 0.2]
  fpca:
    n_components: 3
    min_periods: 252

feature_blocks:
  price: ["garman_klass_rv"]
  surface: ["term_structure_slope"]
  fpca: ["iv_fpca1", "iv_fpca2", "iv_fpca3"]
  macro: ["VIXCLS", "USEPUINDXD"]

models:
  lstm:
    hidden_size: 64
    num_layers: 2
    dropout: 0.1
  ppo:
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
  a2c:
    learning_rate: 0.0007
    n_steps: 2048
    batch_size: 64 